export const DEFAULT_SITE_SETTINGS = {
  store_name: 'Joo Move',
  default_language: 'ar',
  hero_badge: 'نقل منظم. تغليف آمن. بال مرتاح.',
  hero_title: 'ننقل عفشك كأنه بتاعنا',
  hero_desc: 'نقل وتغليف وفك وتركيب الأثاث للمنازل والمكاتب بفريق مدرب وعربيات مجهزة.',
  hero_image: '/joo/hero-moving.jpg',
  hero_image_2: '',
  hero_image_3: '',
  ticker_text_1: 'سنوات خبرة',
  ticker_text_2: 'نقلة مكتملة',
  ticker_text_3: 'رضا العملاء',
  ticker_text_4: 'عميل سعيد',
  about_subtitle: 'عن Joo Move',
  about_title: 'يوم النقل مايبقاش يوم قلق',
  about_text: 'نخطط لكل نقلة ونختار الفريق والخامات والعربية المناسبة قبل التنفيذ.',
  about_image: '/joo/packing-team.jpg',
  why_subtitle: 'فرق الخدمة المنظمة',
  why_title: 'ليه تختار Joo Move؟',
  why_desc: 'فريق واحد مسؤول عن التغليف والفك والتحميل والنقل والتركيب والمتابعة.',
  feature_title_1: 'تغليف احترافي',
  feature_desc_1: 'خامات مناسبة لكل قطعة مع ترقيم واضح.',
  feature_title_2: 'فريق مدرب',
  feature_desc_2: 'عمالة وفنيون يعرفون طريقة التعامل مع الأثاث.',
  feature_title_3: 'التزام بالمواعيد',
  feature_desc_3: 'تنسيق واضح من أول مكالمة حتى التسليم.',
  feature_title_4: 'متابعة مستمرة',
  feature_desc_4: 'مسؤول متابعة واحد طوال رحلة النقل.',
  footer_locations: '[]',
  facebook_link: '',
  instagram_link: '',
  tiktok_link: '',
  support_whatsapp: '',
  admin_whatsapp: '',
  joo_hours_ar: 'يوميًا من 9 صباحًا إلى 11 مساءً',
  joo_hours_en: 'Daily, 9 AM–11 PM',
  joo_area_ar: 'جميع محافظات مصر',
  joo_area_en: 'All governorates across Egypt',
  booking_price_per_tray: '0',
  booking_trays_per_qirat: '0',
  booking_notes: '',
  booking_gallery_images: '[]',
  booking_seo_image_1: '', booking_seo_image_2: '', booking_seo_image_3: '', booking_seo_image_4: '', booking_seo_image_5: ''
};
