export const DEFAULT_SITE_SETTINGS = {
  store_name: 'شركة الرحاب للتنمية الزراعية',
  default_language: 'ar',

  hero_badge: 'توريدات زراعية موثوقة لكبار المزارع',
  hero_title: 'شركة الرحاب للتنمية الزراعية',
  hero_desc: 'شتلات بونيكام برازيلي أصلية، محاصيل علفية، وتوريدات زراعية بجودة ثابتة وخدمة تصل إلى جميع المحافظات.',
  hero_image: '/hero_bg.jpg',
  hero_image_2: '',
  hero_image_3: '',

  ticker_text_1: 'سنة خبرة في التوريدات الزراعية',
  ticker_text_2: 'طن توريدات ومحاصيل',
  ticker_text_3: 'مطابقة جودة',
  ticker_text_4: 'عميل ومزرعة',

  about_subtitle: 'مؤسسة الرحاب للتوريدات',
  about_title: 'خبرة تمتد لسنوات في قطاع المحاصيل والأعلاف',
  about_text: 'انطلقت مؤسسة الرحاب لتكون شريكاً عملياً للمزارعين ومربي الماشية، من اختيار أفضل الشتلات والمحاصيل وحتى التوريد والمتابعة بجودة ثابتة ومواعيد واضحة.',
  about_image: '/hero_bg.jpg',

  why_subtitle: 'الميزة التنافسية',
  why_title: 'لماذا تختار شركة الرحاب؟',
  why_desc: 'معايير واضحة في اختيار الشتلات والمحاصيل والتجهيز والتوصيل، عشان طلبك يوصل بجودة ثابتة وتجربة سهلة.',
  feature_title_1: 'توريد بمقاييس عالمية',
  feature_desc_1: 'شبكة توريد واسعة تضمن وصول المحاصيل والشتلات بأفضل حالة من المصدر مباشرة.',
  feature_title_2: 'جودة منتقاة بعناية',
  feature_desc_2: 'فحص دقيق للشتلات والمحاصيل لضمان أفضل استفادة للمزارع والمربي.',
  feature_title_3: 'نقل وتوصيل مرن',
  feature_desc_3: 'جاهزية لتوصيل الطلبات إلى المحافظات المختلفة حسب حجم الطلب وموعد التجهيز.',
  feature_title_4: 'استشارات زراعية',
  feature_desc_4: 'مساعدة في اختيار الأنسب لطبيعة مشروعك ومساحتك واحتياج مزرعتك.',

  footer_locations: '[]',
  facebook_link: '',
  instagram_link: '',
  tiktok_link: '',
  support_whatsapp: '',
  admin_whatsapp: '',

  booking_price_per_tray: '120',
  booking_trays_per_qirat: '6',
  booking_notes: 'الشحن مجاني، وسيتم التواصل معك لتأكيد موعد التجهيز والتسليم.',
  booking_gallery_images: '[]',
  booking_seo_image_1: '',
  booking_seo_image_2: '',
  booking_seo_image_3: '',
  booking_seo_image_4: '',
  booking_seo_image_5: ''
};
